### ISSUE TITLE
ксеон пидр

### ISSUE THREAD

**Issue by ServerBSvvv** [ObjectTeamDev/ObjectBrawl-v36#2]
чё убрал создание имени? чтоб имя поменять мне пришлось хекс расшифровать гад! норм охд дай сюда!!!!!!!!!!!!!!!!

**Comment by ServerBSvvv** [comment]
да и забыл, ТВОЙ СУКИН КЛИЕНТ НЕ РОБИТ!!!!!!!!!!!!!!!!!!!!!!!!!! ОН НЕ ЗАПУСКАЕТСЯ!!!!!!!!!!!!!!!!!!!!!!! 5 У МЕНЯ АНДРОИД!!!!!!!!!!!!!!!

**Comment by Xeon8297** [comment]
чел ты че там две ложки виагры сожрал? че такой борзый?

**Comment by ServerBSvvv** [comment]
ладно, почему клиент не робит?

**Comment by xmopser** [comment]
> чё убрал создание имени? чтоб имя поменять мне пришлось хекс расшифровать гад! норм охд дай сюда!!!!!!!!!!!!!!!!

А как его расшифровать?
