### ISSUE TITLE
При первом запуске работает, потом не запускается апк, что делать?

### ISSUE THREAD

**Issue by CrCeck-f** [ObjectTeamDev/ObjectBrawl-v36#4]
![Screenshot_2021-07-04-20-59-41-110_com objectteam devbs](https://user-images.githubusercontent.com/72334385/124393290-cd608b80-dd0a-11eb-96a8-263f6a571d09.jpg)

**Comment by brawler888** [comment]
удали и сного установи

**Comment by CrCeck-f** [comment]
я раз 20 пробовал, не помогло

**Comment by brawler888** [comment]
странно

**Comment by Xeon8297** [comment]
это игра делает раз раз раз, надо перезаход
